services:
    hookhub-api:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
            target: production
        container_name: hookhub-api
        restart: unless-stopped
        command: yarn start
        ports:
            - "127.0.0.1:3333:3333"
        env_file:
            - ./.env
        networks:
            - internal
        security_opt:
            - no-new-privileges:true
        tmpfs:
            - /tmp
        read_only: true
        depends_on:
            - hookhub-migrate

    hookhub-migrate:
        build:
            context: .
            dockerfile: Dockerfile.prod
            target: production
        command: yarn migrate up
        env_file:
            - ./.env
        networks:
            - internal
        depends_on:
            - hookhub-db

    hookhub-db:
        image: postgres:17
        container_name: hookhub-pg
        restart: unless-stopped
        env_file:
            - ./.env
        networks:
            - internal
        security_opt:
            - no-new-privileges:true
        volumes:
            - hookhub_pgdata:/var/lib/postgresql/data

    hookhub-rabbitmq:
        image: rabbitmq:3-management
        container_name: hookhub-queue
        restart: unless-stopped
        env_file:
            - ./.env
        networks:
            - internal
        security_opt:
            - no-new-privileges:true
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    hookhub_pgdata:
    rabbitmq_data:

networks:
    internal:
        driver: bridge
